name: infm-grafana-oefening
services:
  influxdb:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=infm
      - DOCKER_INFLUXDB_INIT_BUCKET=timeseries
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=password
    volumes:
      - "./data/influxdb2_data/config:/etc/influxdb2"
      - "./data/influxdb2_data/data:/var/lib/influxdb2"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"   # Grafana web interface
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped

  plc-sim:
    build: ./plc-sim
    depends_on:
      - influxdb
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./plc-sim
          target: /usr/src/app
          initial_sync: true
